# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8997d97e1618d86ad7e3068800131d53"
name = "new-slide-cart"
handle = "new-slide-cart"
application_url = "https://89db-38-253-148-98.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-slide-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_order_edits,read_orders,read_products,read_themes,write_draft_orders,write_order_edits,write_orders,write_products,write_themes"

[auth]
redirect_urls = [
  "https://89db-38-253-148-98.ngrok-free.app/auth/callback",
  "https://89db-38-253-148-98.ngrok-free.app/auth/shopify/callback",
  "https://89db-38-253-148-98.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/hooks/mandatory/customer"
  compliance_topics = [ "customers/data_request", "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/hooks/mandatory/shop"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
