# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8997d97e1618d86ad7e3068800131d53"
name = "new-slide-cart"
application_url = "https://89db-38-253-148-98.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-slide-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_themes,write_themes,read_orders,write_orders,write_order_edits,read_order_edits,write_draft_orders"

[auth]
redirect_urls = [
  "https://89db-38-253-148-98.ngrok-free.app/auth/callback",
  "https://89db-38-253-148-98.ngrok-free.app/auth/shopify/callback",
  "https://89db-38-253-148-98.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://06cf-38-253-148-98.ngrok-free.app/hooks/mandatory/customer"
  customer_data_request_url = "https://06cf-38-253-148-98.ngrok-free.app/hooks/mandatory/customer"
  shop_deletion_url = "https://06cf-38-253-148-98.ngrok-free.app/hooks/mandatory/shop"

[pos]
embedded = false
